# Generated by Django 5.2.8 on 2025-12-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rule_file', models.FileField(upload_to='company_rules/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pincode/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('segment', models.CharField(blank=True, max_length=50, null=True)),
                ('pieces', models.IntegerField(default=0)),
                ('weight', models.FloatField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('month', models.CharField(max_length=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company')),
            ],
            options={
                'unique_together': {('company', 'docket_no', 'month')},
            },
        ),
    ]
