# Generated by Django 5.2.8 on 2026-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='Mysore karnataka', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_no',
            field=models.CharField(default='00000000000', max_length=50, null=True),
        ),
    ]
