# Generated by Django 5.2.8 on 2026-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_company_address_company_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mode',
            field=models.CharField(default='NONE', max_length=100, null=True),
        ),
    ]
