# Generated by Django 5.2.8 on 2026-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_bill_invoice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
    ]
