# Generated by Django 5.2.8 on 2026-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoice_unique_together_alter_invoice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fsc_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='manifest_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='vol_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fsc_percent',
            field=models.IntegerField(default=40, null=True),
        ),
    ]
