# Generated by Django 5.2.8 on 2026-02-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_fsc_amount_bill_manifest_weight_bill_vol_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.invoice'),
        ),
    ]
