# Generated by Django 5.2.8 on 2026-02-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_bill_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='doc_type',
            field=models.CharField(default='NONE', max_length=10),
        ),
    ]
