# Generated by Django 5.2.8 on 2026-02-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_bill_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='inv_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='inv_amt_percent',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='oda_charges',
            field=models.FloatField(default=0, null=True),
        ),
    ]
