# Generated by Django 5.2.8 on 2026-08-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_bill_inv_amount_bill_inv_amt_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('inv_date', models.DateTimeField()),
                ('inv_number', models.CharField(max_length=20)),
                ('cgst', models.FloatField(default=0)),
                ('sgst', models.FloatField(default=0)),
                ('igst', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
            ],
        ),
    ]
