# Generated by Django 5.2.8 on 2026-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_finaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldetails',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
