# Generated by Django 5.2.8 on 2026-08-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_finaldetails_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldetails',
            name='gst_number',
            field=models.CharField(default='000000000', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='finaldetails',
            name='taxable_val',
            field=models.FloatField(default=0),
        ),
    ]
