# Generated by Django 5.2.8 on 2025-12-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='manifest/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedDocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('docket_no', models.CharField(db_index=True, max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('matched', models.BooleanField(default=False)),
                ('manifest_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_no', models.CharField(db_index=True, max_length=50)),
                ('manifest_date', models.DateField(blank=True, null=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifest.manifestupload')),
            ],
        ),
    ]
