# Generated by Django 5.2.8 on 2025-12-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scanneddocket',
            unique_together={('company_name', 'docket_no')},
        ),
    ]
