# Generated by Django 5.2.8 on 2025-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_alter_scanneddocket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocket',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
