# Generated by Django 5.2.8 on 2025-12-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_scanneddocket_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestrecord',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
