# Generated by Django 5.2.8 on 2025-12-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0004_manifestrecord_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestrecord',
            name='pieces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scanneddocket',
            name='pieces',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
