# Generated by Django 5.2.8 on 2026-01-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0005_manifestrecord_pieces_scanneddocket_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocket',
            name='lbh_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanneddocket',
            name='manifest_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanneddocket',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
